
# Dart linter
#include: package:lints/recommended.yaml 

# Flutter linter
#include: package:flutter_lints/flutter.yaml

# Very Good Analysis
include: package:very_good_analysis/analysis_options.yaml

linter:
  rules:


analyzer:
  exclude:
    - '**.freezed.dart'
    - '**.g.dart'
    - '**.gr.dart'
    - '**/generated_plugin_registrant.dart'
