name: fluster
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  flex_color_scheme: ^7.0.2
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  http: ^1.1.0
  intl: any
  isar: ^3.1.0
  isar_flutter_libs: ^3.1.0
  package_info_plus: ^4.0.2
  path_provider: ^2.0.15
  provider: ^6.0.5
  settings_ui: ^2.0.2
  shared_preferences: ^2.1.0

dev_dependencies:
  build_runner: any
  flutter_lints: ^2.0.2
  flutter_test:
    sdk: flutter
  isar_generator: ^3.1.0
  lints: ^2.1.1
  very_good_analysis: ^5.0.0+1


flutter:
  generate: true
  uses-material-design: true
