name: fluster
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  dio: ^5.3.2
  flex_color_scheme: ^7.0.2
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  go_router: ^10.0.0
  http: ^1.1.0
  intl: any
  isar: ^3.1.0
  isar_flutter_libs: ^3.1.0
  json_annotation: ^4.8.1
  lottie: ^2.6.0
  package_info_plus: ^4.0.2
  path_provider: ^2.0.15
  provider: ^6.0.5
  settings_ui: ^2.0.2
  shared_preferences: ^2.1.0
  talker: ^3.1.1
  talker_dio_logger: ^2.3.0
  talker_flutter: ^3.2.9

dev_dependencies:
  build_runner: ^2.4.6
  flutter_lints: ^2.0.2
  flutter_test:
    sdk: flutter
  isar_generator: ^3.1.0
  json_serializable: ^6.7.1
  lints: ^2.1.1
  very_good_analysis: ^5.0.0+1


flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/animations/splash_lottie.json
