name: Build Nightly

# on:
#   push:
#     branches:
#       - main
on: workflow_dispatch


env:
  LLVM_VERSION: "15.0.6"
  FLUTTER_VERSION: "3.10.6"
  TAG_NAME: "nightly"
  PROJECT_NAME: "fluster"

jobs:
  build-and-release-windows:
    name: Build Windows-x64
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        job: 
          - { target: x86_64-pc-windows-msvc, os: windows-latest, arch: x86_64 }
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
      - name: Install LLVM and Clang
        uses: KyleMayes/install-llvm-action@v1
        with:
          version: ${{ env.LLVM_VERSION }}
      - name: Install Flutter 
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          flutter-version: ${{ env.FLUTTER_VERSION }}
          cache: true
      - name: Install project dependencies
        run: flutter pub get
      - name: Generate intermediates
        run: flutter pub run build_runner build --delete-conflicting-outputs
      - name: Enable windows build
        run: flutter create --platforms=windows --project-name=${{env.PROJECT_NAME}} .
      - name: Build release artifacts
        run: flutter build windows --release
      - name: Build archive
        uses: thedoctor0/zip-release@master
        with:
          type: "zip"
          filename: Release-${{env.TAG_NAME}}-windows.zip
          directory: build/windows/runner/Release
      - name: Release Windows-Nightly-Build
        uses: softprops/action-gh-release@v1
        #if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          prerelease: true
          tag_name: ${{env.TAG_NAME}}
          files: build/windows/runner/Release/Release-${{env.TAG_NAME}}-windows.zip


